name: Build rkloaders for Orange Pi 5 / 5B / 5+
on:
  workflow_call:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Prepare deps
        run: |
          sudo apt update
          sudo apt install \
            device-tree-compiler \
            gcc-aarch64-linux-gnu \
            python2 \
            python3-pyelftools
      - name: Restore cached toolchain
        uses: actions/cache/restore@v3
        with:
          path: toolchain-vendor.tar.gz
          key: ${{ runner.os }}-toolchain
          restore-keys: ${{ runner.os }}-toolchain
      - name: Restore cached rkbin repo
        uses: actions/cache/restore@v3
        with:
          path: rkbin.git.tar.gz
          key: ${{ runner.os }}-rkbin
          restore-keys: ${{ runner.os }}-rkbin
      - name: Restore cached vendor u-boot
        uses: actions/cache/restore@v3
        with:
          path: u-boot-vendor.git.tar.gz
          key: ${{ runner.os }}-uboot
          restore-keys: ${{ runner.os }}-uboot
      - name: Restore cached rkloaders
        uses: actions/cache/restore@v3
        with:
          path: out.tar.gz
          key: ${{ runner.os }}-rkloader
          restore-keys: ${{ runner.os }}-rkloader
      - name: Extract and remove archives
        run: |
          for i in rkbin.git u-boot-vendor.git u-boot-mainline.git toolchain-vendor out; do
            if [[ -f $i.tar.gz ]]; then
              tar -xf $i.tar.gz &
            fi
          done
          wait
      - name: Build
        run: ./rkloader.sh
      - name: Pack resources into archives
        run: |
          for i in rkbin.git u-boot-vendor.git u-boot-mainline.git toolchain-vendor out; do
            tar -cf $i.tar.gz $i &
          done
          wait
      - name: Save toolchain
        uses: actions/cache/save@v3
        with:
          path: toolchain-vendor.tar.gz
          key: ${{ runner.os }}-toolchain-${{ hashFiles('toolchain-vendor.tar.gz') }}
      - name: Save rkbin repo
        uses: actions/cache/save@v3
        with:
          path: rkbin.git.tar.gz
          key: ${{ runner.os }}-rkbin-${{ hashFiles('rkbin.git.tar.gz') }}
      - name: Save u-boot vendor repo
        uses: actions/cache/save@v3
        with:
          path: u-boot-vendor.git.tar.gz
          key: ${{ runner.os }}-uboot-${{ hashFiles('u-boot-vendor.git.tar.gz') }}
      - name: Save u-boot mainline repo
        uses: actions/cache/save@v3
        with:
          path: u-boot-mainline.git.tar.gz
          key: ${{ runner.os }}-uboot-${{ hashFiles('u-boot-mainline.git.tar.gz') }}
      - name: Save rkloaders
        uses: actions/cache/save@v3
        with:
          path: out.tar.gz
          key: ${{ runner.os }}-rkloader-${{ hashFiles('out.tar.gz') }}
      - name: Upload all rkloader
        uses: actions/upload-artifact@v3.1.2
        with:
          name: all
          path: |
            out/*
            note.md
          if-no-files-found: error
      - name: Report build versions
        run: cat note.md
      
