name: Build rkloaders for Orange Pi 5 / 5B / 5+
on:
  workflow_call:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Prepare deps
        run: |
          sudo apt update
          sudo apt install \
            device-tree-compiler
      - name: Restore cached toolchain
        uses: actions/cache/restore@v3
        with:
          path: gcc-linaro-7.4.1-2019.02-x86_64_aarch64-linux-gnu.tar.gz
          key: ${{ runner.os }}-toolchain
          restore-keys: ${{ runner.os }}-toolchain
      - name: Restore cached rkbin repo
        uses: actions/cache/restore@v3
        with:
          path: rkbin.git.tar.gz
          key: ${{ runner.os }}-rkbin
          restore-keys: ${{ runner.os }}-rkbin
      - name: Restore cached u-boot repo
        uses: actions/cache/restore@v3
        with:
          path: u-boot-orangepi.git.tar.gz
          key: ${{ runner.os }}-uboot
          restore-keys: ${{ runner.os }}-uboot
      # - name: Restore cached rkloaders
      #   uses: actions/cache/restore@v3
      #   with:
      #     path: out.tar.gz
      #     key: ${{ runner.os }}-rkloader
      #     restore-keys: ${{ runner.os }}-rkloader
      - name: Extract and remove archives
        run: |
          for i in rkbin.git u-boot-orangepi.git gcc-linaro-7.4.1-2019.02-x86_64_aarch64-linux-gnu out; do
            if [[ -f $i.tar.gz ]]; then
              tar -xf $i.tar.gz &
            fi
          done
          wait
      - name: Build
        run: ./rkloader.sh
      - name: Pack resources into archives
        run: |
          for i in rkbin.git u-boot-orangepi.git gcc-linaro-7.4.1-2019.02-x86_64_aarch64-linux-gnu out; do
            tar -cf $i.tar.gz $i &
          done
          wait
      - name: Save toolchain
        uses: actions/cache/save@v3
        with:
          path: gcc-linaro-7.4.1-2019.02-x86_64_aarch64-linux-gnu.tar.gz
          key: ${{ runner.os }}-toolchain-${{ hashFiles('gcc-linaro-7.4.1-2019.02-x86_64_aarch64-linux-gnu.tar.gz') }}
      - name: Save rkbin repo
        uses: actions/cache/save@v3
        with:
          path: rkbin.git.tar.gz
          key: ${{ runner.os }}-rkbin-${{ hashFiles('rkbin.git.tar.gz') }}
      - name: Save u-boot repo
        uses: actions/cache/save@v3
        with:
          path: u-boot-orangepi.git.tar.gz
          key: ${{ runner.os }}-uboot-${{ hashFiles('u-boot-orangepi.git.tar.gz') }}
      # - name: Save rkloaders
      #   uses: actions/cache/save@v3
      #   with:
      #     path: out.tar.gz
      #     key: ${{ runner.os }}-rkloader-${{ hashFiles('out.tar.gz') }}
      - name: Upload all rkloader
        uses: actions/upload-artifact@v3.1.2
        with:
          name: all
          path: |
            out/*
            versions
          if-no-files-found: error
      - name: Upload rkloader for 5
        uses: actions/upload-artifact@v3.1.2
        with:
          name: opi5
          path: out/rkloader-3588-orangepi-5-*
      - name: Upload rkloader for 5 (SATA)
        uses: actions/upload-artifact@v3.1.2
        with:
          name: opi5sata
          path: out/rkloader-3588-orangepi-5_sata-*
      - name: Upload rkloader for 5b
        uses: actions/upload-artifact@v3.1.2
        with:
          name: opi5b
          path: out/rkloader-3588-orangepi-5b-*
      - name: Upload rkloader for 5-plus
        uses: actions/upload-artifact@v3.1.2
        with:
          name: opi5plus
          path: out/rkloader-3588-orangepi-5_plus-*
      - name: Report build versions
        run: cat versions
      
