name: Release rkloaders for Orange Pi 5 / 5B / 5+ nightly
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
permissions:
  contents: write
jobs:
  build:
    uses: ./.github/workflows/build.yml
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
     - name: Download artifacts
       uses: actions/download-artifact@v4.1.8
       with:
         name: all
     - name: Display structure of downloaded files
       run: ls -R
     - name: Release
       uses: ncipollo/release-action@v1
       with:
          name: Nightly
          tag: nightly
          artifacts: out/*
          allowUpdates: true
          removeArtifacts: true
          bodyFile: note.md
