name: Release rkloaders for Orange Pi 5 / 5B / 5+ nightly
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v3.5.2
     - name: Build
       uses: ./.github/workflows/build
     - name: Release
       uses: softprops/action-gh-release@v1
       with:
         body_path: versions
         draft: true
         name: Nightly
         tag_name: nightly
         files: out/rkloader-3588-orangepi-5*