name: Release rkloaders for Orange Pi 5 / 5B / 5+ nightly
on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
     - name: Download artifacts
       uses: actions/download-artifact@v3
       with:
         name: all
     - name: Display structure of downloaded files
       run: ls -R